### ISSUE TITLE
Auto-rehash hook is not executed after gem installation

### ISSUE THREAD

**Issue by dnrce** [sous-chefs/ruby_rbenv#213]
### Cookbook version
2.0.7

### Chef-client version
13.6.4

### Platform Details
Oracle Linux 7.3

### Scenario:
Default rbenv behavior is to automatically rehash shims after installing gems. Installing a gem resource with `rbenv_gem` does not trigger a rehash.

### Steps to Reproduce:
1. Use `rbenv_gem` to install a gem with an executable.

### Expected Result:
The new executable is present in the output of `rbenv shims`.

### Actual Result:
The new executable is not present in the output of `rbenv shims`.

**Comment by damacus** [comment]
I've never had rehash actually do that, according to the docs it doesn't? https://github.com/rbenv/rbenv#rbenv-rehash

I'm probably missing some thing here. Would love to have some docuemtnation pointing to the way it's supposed to work. We just run `gem install` under the hood so it should be piggy backing on the back of rbenv behaviour.

**Comment by dnrce** [comment]
`rbenv_gem` calls the gem binary directly, which is different from calling it via rbenv, which executes the hook:
```
[root@default-oracle-73 vagrant]# /opt/rbenv/versions/2.3.1/bin/gem install --no-document rake
Fetching: rake-12.3.1.gem (100%)
Successfully installed rake-12.3.1
1 gem installed
[root@default-oracle-73 vagrant]# rbenv shims | grep rake
[root@default-oracle-73 vagrant]# RUBY_VERSION=2.3.1 rbenv exec gem install --no-document rake
YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0).
Fetching: rake-12.3.1.gem (100%)
Successfully installed rake-12.3.1
1 gem installed
[root@default-oracle-73 vagrant]# rbenv shims | grep rake
/opt/rbenv/shims/rake
```

**Comment by damacus** [comment]
I'm totally missing what you're saying here. According to the rbenv documentation you do just call the gem binary
https://github.com/rbenv/rbenv#installing-ruby-gems

We can totally call `rbenv exec gem` instead though. It just isn't in the documentation, so I haven't used it!

**Comment by aried3r** [comment]
> Default rbenv behavior is to automatically rehash shims after installing gems. Installing a gem resource with rbenv_gem does not trigger a rehash.

Since 1.0 rbenv does [automatically rehash](https://github.com/rbenv/rbenv/issues/967#issuecomment-277507719). There's also a [test for it](https://github.com/rbenv/rbenv/blob/59785f6762e9325982584cdab1a4c988ed062020/test/init.bats#L14-L18).

But if I understand the [documentation](https://github.com/rbenv/rbenv/#how-rbenv-hooks-into-your-shell) and the test correctly, it does this only if you setup your shell correctly, so rbenv can hook into it. I think that's why this cookbook might "fail" to rehash automatically, because it's not using any bash profile or anything (correct me if I'm wrong).
It's why I use https://github.com/sous-chefs/ruby_rbenv#rehash in my own cookbook after installing everything.

**Comment by damacus** [comment]
Closing as resolved. But leaving unlocked 👍
