### ISSUE TITLE
Initial bootstrapping not working

### ISSUE THREAD

**Issue by mperham** [sous-chefs/ruby_rbenv#31]
```
  "rbenv" => {
    "git_ref" => "v0.4.0",
    "rubies" => ["1.9.3-p374"],
    'global' => '1.9.3-p374',
    "gems" => {
      "1.9.3-p374" => [{"name" => "bundler"}]
    }
  },
```

``` ruby
require_recipe 'ruby_build'
require_recipe 'rbenv::system'
```

Results in this:

```
[2013-01-24T16:49:16-08:00] INFO: Processing script[rbenv install 1.9.3-p374 (system)] action run (/opt/chef-solo/current/cookbooks/rbenv/providers/script.rb line 28)

================================================================================
Error executing action `run` on resource 'script[rbenv install 1.9.3-p374 (system)]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20130124-17061-1l3nqso" ----
STDOUT: 
STDERR: rbenv: version `global' not installed
rbenv: no such command `install'
---- End output of "bash"  "/tmp/chef-script20130124-17061-1l3nqso" ----
Ran "bash"  "/tmp/chef-script20130124-17061-1l3nqso" returned 1
```

**Comment by antoinerg** [comment]
Exact same problem here!

**Comment by MSch** [comment]
Yep here too. Any ideas how to track this down?

**Comment by jetheredge** [comment]
I'm having this error as well, it appears that when you run "require_recipe 'ruby_build'" it does not get added into the nodes runlist. On line 85 or rbenv/providers/ruby.rb it has a check to see if ruby_build is installed, and it is looking in the run list for the node by calling node.recipe?("ruby_build").

Unfortunately this call is returning false, so the script thinks ruby_build is not installed and skips installing the ruby version you specified. Then later you get the error while trying to set the global gem version, because the ruby install was skipped.

I'm not sure how to reliably check if ruby_build has been loaded by a call to "require_recipe", but for now I have simply removed the check in my local version.

**Comment by jelder** [comment]
+1

**Comment by michiels** [comment]
I think this is because you probably use a new definition in your node attributes and ruby-build is not updated with these new definitions yet. At least, that was the problem when I ran into this exact same problem. To reproduce, I did two things:

Set attribute `node['ruby_build']['upgrade'] = true` and run `./install` in `/var/chef/ruby-build` so ruby-build correctly updates its own version list in `/usr/local/share/ruby-build`.

However, I was not able to figure out why the `ruby-build` cookbook seems to fail because the code in the default recipe looks good. But, I think this is a `ruby-build` problem and not a `rbenv` problem.

**Comment by johnbellone** [comment]
Can this get merged in?

**Comment by jetheredge** [comment]
This pull fixed the issues I was seeing.

**Comment by piousbox** [comment]
For me, adding more configuration to the role seems to work, as suggested by @michiels 

default_attributes(
                   "nagios" => {
                     "server_role" => "monitoring"
                   },
                   'ruby_build' => {
                     'upgrade' => true
                   }
)
